### ISSUE TITLE
old-time dependency wont install on Windows

### ISSUE THREAD

**Issue by Kamayuq** [haskell/old-time#10]
Configuring old-time-1.1.0.3...
cabal.exe: The package has a './configure' script. If you are on Windows, This
requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
are not on Windows, ensure that an 'sh' command is discoverable in your path.
cabal: Leaving directory 'C:\Users\khipu\AppData\Local\Temp\cabal-tmp-8928\old-time-1.1.0.3'

I have no intention of installing MinGW+MSYS or Cygwin

**Comment by gbaz** [comment]
Well then I guess you can't use this package.
