### ISSUE TITLE
cannot reinstall old-time after installing Haskell Platform 8.0.1

### ISSUE THREAD

**Issue by KeesBleijenberg** [haskell/old-time#3]
I work on a 64 bits computer with Windows 7.
Installing cpphs-1.20.1 and haskell-scr-exts and hlint fails on installing old-time-1.1.0.3. 
Haskell platform 8.0.1. let me install postgresql-libpq, This was not possible with older versions. These version had linker problems. But with this new Haskell platform version, new problems pop up.

The error message I got after 'cabal install old-time' is:
Resolving dependencies...
Configuring old-time-1.1.0.3...
Failed to install old-time-1.1.0.3
Build log ( C:\Users\kees\AppData\Roaming\cabal\logs\old-time-1.1.0.3.log ):
Configuring old-time-1.1.0.3...
Warning: The flag --enable-executable-profiling is deprecated. Please use
--enable-profiling instead.
cabal.exe: The package has a './configure' script. If you are on Windows, This
requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
are not on Windows, ensure that an 'sh' command is discoverable in your path.
cabal: Leaving directory 'D:\Temp\cabal-tmp-5888\old-time-1.1.0.3'
cabal: Error: some packages failed to install:
old-time-1.1.0.3 failed during the configure step. The exception was:
ExitFailure 1

I have a mingw installation on my computer.

Kees

**Comment by gbaz** [comment]
Did you change your cabal config file to reflect the mingw location, as described on the platform download page?

**Comment by KeesBleijenberg** [comment]
Yes I did. But I did it wrong. I.e. I had:
extra-include-dirs: D:\Program Files\Haskell Platform\8.0.1\mingw\include -- my comment
The comment was the problem.
Thanks for your help.

**Comment by chwarr** [comment]
For those like me who might already have something in `extra-prog-path`, the delimiter for this setting (on Windows, at least) is the semi-colon, ';'. That is,

```
...
extra-prog-path: c:\the first\path;d:\the second path
...
```

is a way to have multiple paths in your cabal config file.

**Comment by nboldi** [comment]
I think the version number of the base dependency also have to change to something like: 
`base       >= 4.7 && < 5.0,` I could only install the package by locally changing the cabal file.

**Comment by OnurGumus** [comment]
Same problem with Windows here. With Haskell 7.x, it works fine.

**Comment by OnurGumus** [comment]
Oh I solved it by applying Step 3 of the Haskell platform installer:

Modify your cabal config file (you can verify the location by running "cabal user-config init") to contain the following lines: 
extra-prog-path: C:\Program Files\Haskell Platform\8.0.1\msys\usr\bin
extra-lib-dirs: C:\Program Files\Haskell Platform\8.0.1\mingw\lib
extra-include-dirs: C:\Program Files\Haskell

**Comment by madscientist42** [comment]
Followed instructions.  If you use a stock install of the platform for Windows...it doesn't seem to have bash/sh in the mix.  If you supply a Cygwin bash session to cabal to work with, it doesn't mess up with the missing /bin/sh concern but screws up in a manner of the other outstanding issue.

This isn't portable, gang...

**Comment by alex-trueman** [comment]
This is not as straight-forward an install process as it should be. Why can't the Windows installer modify the `config` file accordingly. In my install the folder version name is `8.02-a\` but the folder name in the instructions is `8.02\`. Easy enough to fix once I found the issue but a bit of an awkward process.

**Comment by ErikSchierboom** [comment]
I had the same problem as @truemoid, where the instructions did not match the actual folder name.

**Comment by gbaz** [comment]
The platform release process has automated that documentation now, so the folder name in the instructions is derived from the same source as the one in the installer. I think that should resolve this issue.

**Comment by lvth** [comment]
> 
> 
> Oh I solved it by applying Step 3 of the Haskell platform installer:
> 
> Modify your cabal config file (you can verify the location by running "cabal user-config init") to contain the following lines:
> extra-prog-path: C:\Program Files\Haskell Platform\8.0.1\msys\usr\bin
> extra-lib-dirs: C:\Program Files\Haskell Platform\8.0.1\mingw\lib
> extra-include-dirs: C:\Program Files\Haskell

I really appreciate your help.
:)
