### ISSUE TITLE
Unable to Install `old-time-1.1.0.3` on Windows under Haskell Platform

### ISSUE THREAD

**Issue by iamrecursion** [haskell/old-time#7]
I've been trying to install some modules that depend (indirectly, in most cases) on `old-time` on windows today, and the install fails. It can be reproduced by attempting a `cabal install old-time` in by itself, but does not occur in a `cabal` sandbox. The crux of the issue seems to arise form missing interfaces in `old-locale` as follows:
```
Preprocessing library old-time-1.1.0.3...
[1 of 1] Compiling System.Time      ( dist\build\System\Time.hs, dist\build\System\Time.o )

System\Time.hsc:117:1: error:
    Failed to load interface for `System.Locale'
    There are files missing in the `old-locale-1.0.0.7' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
```

This is occurring on a fresh install of Haskell Platform. It looks like the version of `old-locale` bundled with the platform is the same version number (`1.0.0.7`) as is downloaded into a sandbox, but not the same contents. Indeed, forcing a `ghc-pkg unregister old-locale --force`, `cabal install old-locale` before trying `cabal install old-time` again fixes the issue. 

Let me know if there is any additional information I can provide that will be helpful. I'm not really sure what you can do yourself to fix this, but I figured I'd report it anyway.

**Comment by gbaz** [comment]
The platform hasn't shipped old-locale since 7.10.3? Is this a prior version of the platform then?

**Comment by iamrecursion** [comment]
Much more recent... perhaps I ended up with a corrupt install somehow.

**Comment by gbaz** [comment]
which version precisely -- 32 or 64 bit, which ghc, minimal or core?

it may be an issue with one installer in particular...

**Comment by iamrecursion** [comment]
It was the 64-bit re-release of 8.0.2 due to the Windows 10 Creators update issue. Full installer. 

I've since moved away from it to use slack for managing my GHC installs.

**Comment by Rizary** [comment]
Still having the same issue with most recent HP. The error: 
```
Failed to build old-time-1.1.0.3 (which is required by exe:backend from
backend-0.0.0.1). The failure occurred during the configure step. The build
process terminated with exit code 77
```

it is the same as the time package, but i can fix it by using this solution https://github.com/haskell/cabal/issues/4515 (perhaps it is the same?).

Then i try to build old-time locally and get this error:
```
"D:\Engineer\IDE\cmder\vendor\git-for-windows\usr\bin\sh.exe" "./configure" "--with-compiler=ghc" "--prefix=D:\cabal-store\ghc-8.2.1\time-1.8.0.3-bc0e8a8fd28aee95b7863efc907e80c26e23d4aa" "--bindir=D:\cabal-store\ghc-8.2.1\time-1.8.0.3-bc0e8a8fd28aee95b7863efc907e80c26e23d4aa\bin" "--libdir=D:\cabal-store\ghc-8.2.1\time-1.8.0.3-bc0e8a8fd28aee95b7863efc907e80c26e23d4aa\lib" "--libexecdir=D:\cabal-store\ghc-8.2.1\time-1.8.0.3-bc0e8a8fd28aee95b7863efc907e80c26e23d4aa\libexec" "--datadir=D:\cabal-store\ghc-8.2.1\time-1.8.0.3-bc0e8a8fd28aee95b7863efc907e80c26e23d4aa\share" "--sysconfdir=D:\cabal-store\ghc-8.2.1\time-1.8.0.3-bc0e8a8fd28aee95b7863efc907e80c26e23d4aa\etc" "CC=D:\Engineer\ProgLang\Haskell\Haskell Platform\8.2.1\mingw\bin\gcc.exe"
checking for gcc... D:\Engineer\ProgLang\Haskell\Haskell Platform\8.2.1\mingw\bin\gcc.exe
checking whether the C compiler works... no
configure: error: in `/d/Engineer/ProgLang/Haskell/hackage-matrix-builder/dist-newstyle/tmp/src-7100/time-1.8.0.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
