### ISSUE TITLE
old-time fails to install

### ISSUE THREAD

**Issue by lap00zza** [haskell/old-time#8]
Hello. I decided to install `hoogle` and ran into a weird issue. old-time just does not install. I tried quite a few solutions after googling this issue, but none seem to help. Please can I get some help.

![cabal](https://user-images.githubusercontent.com/8621583/31140151-38d7d1dc-a891-11e7-8d4c-d18b785c8afd.png)

#### Additional Info:
* I am using Windows 8.1 64 bit
* Cabal is version 2.0.0.0
* GHC is version 8.2.1
* Haskell is installed using Haskell Platform Install full 64 bit (http://www.haskell.org/platform/windows.html)
* My cabal config https://gist.github.com/lap00zza/0aebd4520ddba31ee019f6f2cbbd90a0

**Comment by gbaz** [comment]
Did you modify your cabal config file as in step 2 of the above link?

**Comment by lap00zza** [comment]
yes I modified.  I have pasted it. Please check my gist link above. (I hope thats how we are supposed to modify)

**Comment by gbaz** [comment]
@hvr do you think this is perhaps related to https://github.com/haskell/old-time/issues/5 ?

**Comment by gbaz** [comment]
Also, here's a rather silly idea, but who knows. It looks like you're running from the mingw prompt. Do you get the same result running from a standard dos prompt?

**Comment by lap00zza** [comment]
Hi. Yes I seem to be getting the same error in the cmd prompt as well
![cabal_dos](https://user-images.githubusercontent.com/8621583/31142465-00ec5d90-a898-11e7-8c07-f45df85b9ce4.png)

**Comment by lap00zza** [comment]
Ok this is really weird but this issue got fixed. This is what I did:

* Uninstalled Haskell Platform (previously I installed it to `E:\Program Files`)
* Uninstalled Stack
* Deleted cabal config
* Installed Haskell Platform, but this time to `C:\Program Files`
* Ran `cabal install old-time`
* And it worked. No more errors.
